### ISSUE TITLE
Make sure optimization actually stops when threshold is achieved

### ISSUE THREAD

**Issue by ljchang** [cosanlab/emotionCF#21]
Might only be working with number of iterations.

**Comment by ngreenstein** [comment]
**For `NNMF_multiplicative`:**

Based on the existing code, I'm assuming the threshold in question is `fit_residual` falling below `fit_error_limit`. 128c7bf implements this.

**For `NNMF_sgd`:**

Currently, nothing analogous to `fit_error_limit` exists, although the docstring suggests that it should. That's easy to add, but (assuming this is the goal), we'd also have to add a step that computes something analogous to `fit_residual`. I think that requires calling `predict()` after each iteration, which would have a performance cost.

Do you think it's worth implementing this for `NNMF_sgd`? Happy to do it if so, just wanted to check if it makes sense.

**Comment by ljchang** [comment]
I think the pattern that might make more sense is to loop over iterations and then break of residual is lower than the tolerance. 

Check out some of the sklearn algorithms, such as NNMF https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/decomposition/nmf.py

**Comment by ngreenstein** [comment]
Sure, can definitely do that. It probably also makes sense to check every 10 iterations, as sklearn does, instead of each time.

One question on the math: sklearn is calculating error by comparing current error to the initial error from before fitting began. With multiplicative updating, `(previous error - current error) / initial error` [(link)](https://github.com/scikit-learn/scikit-learn/blob/3ab22f973fb1ff1643fb980075559316478f7bd4/sklearn/decomposition/nmf.py#L824), and with coordinate descent, `current error / initial error` [(link)](https://github.com/scikit-learn/scikit-learn/blob/3ab22f973fb1ff1643fb980075559316478f7bd4/sklearn/decomposition/nmf.py#L518).

Should we do the same?

**Comment by ljchang** [comment]
Here are some quick thoughts

1) Let's go with percent error threshold
2) Let's add a rate of change threshold
3) let's try to match Sci-kit learn's defaults in terms of order of operations.
